json.name @phone.name
json.camera @phone.back_camera
json.price @phone.price
json.camera @phone.font_camera
json.photo_url @phone.photo_url
json.display @phone.display
json.os @phone.os
json.cpu @phone.cpu
json.ram @phone.ram
json.storage @phone.storage
json.sp_storage @phone.sp_storage
json.sim @phone.sim
json.battery @phone.battery
json.category_id @phone.category_id
json.flag @phone.flag
json.description @phone.description
json.created_at @phone.created_at
json.updated_at @phone.updated_at
